// packages/host/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <Header />
    <div>Name: host</div>
    <div>
      count: {{ count }}
    </div>
    <div>
      <button @click="addOne">
        Add one
      </button>
    </div>
    <div>
      <router-view></router-view>
    </div>
    <!-- <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div> -->
  </div>
</template>

<script>
import { defineAsyncComponent } from 'vue';

// import Header from 'remote/Header'

const Header = defineAsyncComponent(() => import("remote/Header"))

export default {

  components: {
    Header
  },

  computed: {
    count() {
      return this.$store.state.count;
    }
  },

  methods: {
    addOne() {
      this.$store.commit('addOne')
    }
  }

}
</script>

// packages/react-host/src/App.jsx
import React, {useRef, useEffect} from "react";
import ReactDOM from "react-dom";

import placeHeader from 'remote/placeHeader'

import "./index.scss";

const App = () =>{

  const headerRef = useRef(null);

  useEffect(() => {
    placeHeader(headerRef.current)
  })

  return (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div ref={headerRef}></div>
    <div>Name: react-host</div>
    <div>Framework: react</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
)}
ReactDOM.render(<App />, document.getElementById("app"));
